trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'connectedServiceNameARM'  # Azure subscription connected to Azure DevOps
  resourceGroup: 'python-app'  # Azure resource group for ACI and ACR
  acrName: 'sampleapp'  # Azure Container Registry name
  acrServiceConnection: 'sampleapp'  # Azure service connection for ACR
  containerName: 'python-app-container'  # Azure Container Instance name
  imageName: 'python-app'  # Docker image name
  containerRegistry: 'sampleapp.azurecr.io'  # ACR registry URI (including the region, e.g., azurecr.io)
  imageTag: '$(Build.BuildId)'  # Unique tag based on Build ID (e.g., 1234, 1235, etc.)
  # Cache variables
  DOCKER_BUILDKIT: 1  # Enable BuildKit for better Docker performance
  CACHE_VERSION: 'v1'  # Increment this when you need to invalidate the cache

jobs:
- job: BuildAndDeploy
  displayName: 'Build Docker Image, Push to ACR, and Deploy to ACI'
  pool:
    vmImage: 'ubuntu-latest'  # Use Ubuntu for the build environment

  steps:
    # Step 1: Check and Create Resource Group if Needed
    - task: AzureCLI@2
      displayName: 'Check and Create Resource Group'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Checking if Resource Group $(resourceGroup) exists..."
          rg_exists=$(az group show --name $(resourceGroup) --query "name" -o tsv 2>/dev/null || echo "")
          if [ -z "$rg_exists" ]; then
            echo "Resource Group $(resourceGroup) does not exist. Creating it..."
            az group create --name $(resourceGroup) --location eastus
          else
            echo "Resource Group $(resourceGroup) already exists. Skipping creation."
          fi

    # Step 2: Check and Create ACR if Needed
    - task: AzureCLI@2
      displayName: 'Check and Create Azure Container Registry (ACR)'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Checking if ACR $(acrName) exists..."
          acr_exists=$(az acr show --name $(acrName) --resource-group $(resourceGroup) --query "name" -o tsv 2>/dev/null || echo "")
          if [ -z "$acr_exists" ]; then
            echo "Creating ACR $(acrName)..."
            az acr create \
              --name $(acrName) \
              --resource-group $(resourceGroup) \
              --sku Basic \
              --admin-enabled true
            echo "Waiting for ACR to be ready..."
            sleep 30  # Give ACR some time to finish provisioning
          else
            echo "ACR $(acrName) already exists."
          fi
          
          # Enable admin access if not already enabled
          echo "Ensuring admin access is enabled on ACR..."
          az acr update --name $(acrName) --admin-enabled true

    # Step 3: Restore Docker cache
    - task: Cache@2
      displayName: 'Restore Docker cache'
      inputs:
        key: 'docker-cache-$(Agent.OS)-$(CACHE_VERSION) | "$(Build.SourcesDirectory)/Dockerfile"'
        restoreKeys: |
          docker-cache-$(Agent.OS)-$(CACHE_VERSION)
          docker-cache-$(Agent.OS)
        path: '$(Pipeline.Workspace)/.docker-cache'
      
   # Step 4: Build, Scan, and Push Docker Image using Azure CLI with caching
    - task: AzureCLI@2
      displayName: 'Build, Scan, and Push Docker Image to ACR'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create cache directory if it doesn't exist
          mkdir -p $(Pipeline.Workspace)/.docker-cache

          # Login to ACR using Azure CLI
          echo "Logging in to ACR $(acrName)..."
          az acr login --name $(acrName)

          # Pull latest image for cache (if it exists)
          echo "Trying to pull latest image for cache..."
          docker pull $(containerRegistry)/$(imageName):latest || true

          # Build the Docker image with cache options
          echo "Building Docker image with cache..."
          docker build \
            --cache-from=$(containerRegistry)/$(imageName):latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t $(containerRegistry)/$(imageName):$(imageTag) \
            -t $(containerRegistry)/$(imageName):latest \
            -f $(Build.SourcesDirectory)/Dockerfile \
            $(Build.SourcesDirectory)

          # Install Trivy
          echo "Installing Trivy scanner..."
          wget https://github.com/aquasecurity/trivy/releases/download/v0.62.1/trivy_0.62.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.62.1_Linux-64bit.deb

          # Run Trivy image scan (scan local image before pushing)
          echo "Running Trivy vulnerability scan (warn only)..."
          trivy image --exit-code 0 --severity HIGH,CRITICAL --ignore-unfixed $(containerRegistry)/$(imageName):$(imageTag)

          # Push the Docker images to ACR
          echo "Pushing Docker images to ACR..."
          docker push $(containerRegistry)/$(imageName):$(imageTag)
          docker push $(containerRegistry)/$(imageName):latest

          # Verify image was pushed successfully
          echo "Verifying image was pushed to ACR..."
          az acr repository show --name $(acrName) --repository $(imageName)

    # Step 4: Deploy to Azure Container Instances
    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Instances'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Get ACR credentials
          echo "Getting ACR credentials..."
          acrUsername=$(az acr credential show --name $(acrName) --query username -o tsv)
          acrPassword=$(az acr credential show --name $(acrName) --query "passwords[0].value" -o tsv)
          
          echo "Using registry: $(containerRegistry)"
          echo "Using image: $(containerRegistry)/$(imageName):$(imageTag)"
          
          # Verify the image exists in ACR
          echo "Verifying image exists in ACR..."
          az acr repository show --name $(acrName) --image $(imageName):$(imageTag) || echo "WARNING: Image may not exist in registry"
          
          echo "Deploying to Azure Container Instances..."
          az container create \
            --name $(containerName) \
            --resource-group $(resourceGroup) \
            --image $(containerRegistry)/$(imageName):$(imageTag) \
            --cpu 1 \
            --memory 1.5 \
            --ports 5000 \
            --dns-name-label python-app-demo \
            --registry-login-server $(containerRegistry) \
            --registry-username "$acrUsername" \
            --registry-password "$acrPassword" \
            --os-type Linux
          
          # Verify deployment status
          echo "Checking container status..."
          az container show --name $(containerName) --resource-group $(resourceGroup) --query instanceView.state